name: ECR Credential Updater
description: |
  Automatically updates AWS EC2 Container Registry credentials in Rancher.
version: v1.1.0
category: Applications
maintainer: John Engelman <john.engelman@objectpartners.com>
