name: Apache Zookeeper
description: |
  (Experimental) Zookeeper cluster
version: 3.4.8-rancher1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
minimum_rancher_version: v0.59.0
license: 
