rancher-alarms-${ENVIRONMENT}:
  environment:
    ALARM_EMAIL_ADDRESSES: ${ALARM_EMAIL_ADDRESSES}
    ALARM_EMAIL_FROM: ${ALARM_EMAIL_FROM}
    ALARM_EMAIL_PASS: ${ALARM_EMAIL_PASS}
    ALARM_EMAIL_SMTP_HOST: ${ALARM_EMAIL_SMTP_HOST}
    ALARM_EMAIL_SMTP_PORT: '${ALARM_EMAIL_SMTP_PORT}'
    ALARM_EMAIL_SSL: ${ALARM_EMAIL_SSL}
    ALARM_EMAIL_SUBJECT: "${ALARM_EMAIL_SUBJECT}"
    ALARM_EMAIL_USER: ${ALARM_EMAIL_USER}
    ALARM_EMAIL_TEMPLATE: ${ALARM_EMAIL_TEMPLATE}
    ALARM_FILTER: ${ALARM_FILTER}
    ALARM_MONITOR_HEALTHY_THRESHOLD: '${ALARM_MONITOR_HEALTHY_THRESHOLD}'
    ALARM_MONITOR_INTERVAL: '${ALARM_MONITOR_INTERVAL}'
    ALARM_MONITOR_UNHEALTHY_THRESHOLD: '${ALARM_MONITOR_UNHEALTHY_THRESHOLD}'
    ALARM_POLL_INTERVAL: '${ALARM_POLL_INTERVAL}'
    ALARM_SLACK_BOTNAME: ${ALARM_SLACK_BOTNAME}
    ALARM_SLACK_CHANNEL: '${ALARM_SLACK_CHANNEL}'
    ALARM_SLACK_TEMPLATE: "${ALARM_SLACK_TEMPLATE}"
    ALARM_SLACK_WEBHOOK_URL: ${ALARM_SLACK_WEBHOOK_URL}
    RANCHER_ACCESS_KEY: ${RANCHER_ACCESS_KEY}
    RANCHER_ADDRESS: ${RANCHER_ADDRESS}
    RANCHER_PROJECT_ID: ${RANCHER_PROJECT_ID}
    RANCHER_SECRET_KEY: ${RANCHER_SECRET_KEY}
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: ndelitski/rancher-alarms
