name: Rancher Alarms
description: |
  Send notifications when a stack or service degrades in Rancher.
version: v0.0.0
category: Monitoring
maintainer: "Chris Fordham <chris@fordham-nagy.id.au>"
minimum_rancher_version: v0.1.0
license: Apache 2.0
